// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbcgxvbnxxcnpwiljyur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiY2d4dmJueHhjbnB3aWxqeXVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTE0OTgsImV4cCI6MjA2NTUyNzQ5OH0.yMuzO1911kX9lUq3P8s4Vn_MSkqHxMKLtCpXE2hFY3c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);